name: RSpec and Rubocop

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: RSpec and Rubocop
    timeout-minutes: 3
    services:
      redis:
        image: 'redis:6'
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      REDIS_URL: redis://localhost:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
      - name: Run rspec
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop
#      - name: Upload coverage directory
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: coverage-report
#          path: coverage/
